---
- name: AUTOMATIC IPv6 CONFIG
  hosts: switches
  gather_facts: false 
  
  tasks:
    
    - name: DISPLAYING CSR1000v
      ios_config:
        parents: "interface loopback1000"
        lines:
          - description IPv6 ADDRESS
          - ipv6 address 2001:db8:acad:1::1/64 
          - ipv6 address fe80::1:1 link-local
    
    - name: SHOW IPv6 INTERFACE BRIEF CSR1000v
      ios_command: 
        commands : 
          - show ipv6 interface brief 
      register: outputCSR

    - name: SAVE OUTPUT CSR1000v ./ios_configurations/
      copy:
        content: "{{ outputCSR.stdout[0] }}"
        dest: "ios_configurations/IPv6_output_{{ inventory_hostname }}.txt"

